[release] added metrics to locust
dojot/dojot pull request #1659
Opened 2020-08-20 18:35 UTC by jonaphael

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2020-09-03 17:22 UTC, eduardogmisiuk requested changes
Nice! I left only one comment.

2020-09-03 17:22 UTC, eduardogmisiuk commented on connector/mqtt/locust/src/mqtt_locust/mqtt_client.py
> +        Utils.fire_locust_failure(
I don't think it should be counted as a failure.

2020-09-11 11:57 UTC, eduardogmisiuk submitted a review, later dismissed

2020-09-11 13:55 UTC, thiagodpf approved these changes
I believe that Eduardo is more inside the logic involved in this code, but in my view, it's ok.

2020-10-16 12:24 UTC, mprevide commented
Maybe you can close this PR and open another one to development.  @jonaphael

2021-01-13 19:26 UTC, mprevide commented
I change the PR to a feature branch :)
So, now I can merge this PR!

2021-01-13 19:27 UTC, mprevide approved these changes

2021-01-13 19:44 UTC, merged