feat: authentication and device authorization service by user and password
dojot/dojot pull request #2344
Opened 2021-11-22 02:43 UTC by gilmaicor

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-11-24 14:20 UTC, rodrigoaasm requested changes
Good job. I left some comments.

2021-11-25 13:26 UTC, luissajunior requested changes

2021-11-25 15:28 UTC, gilmaicor commented on connector/http-agent/app/Utils.js
> +  const date = moment(ts, true);
Feito.

2021-11-25 15:28 UTC, gilmaicor commented on iam/device-basic-authentication/app/kafka/ConsumerMessages.js
> +      `^.+${configMessenger['consume.topic.tenancy'].replace(/\./g, '\\.')}`,
Feito.

2021-11-25 15:28 UTC, gilmaicor commented on iam/device-basic-authentication/app/kafka/ConsumerMessages.js
> +      `^.+${configMessenger['consume.topic.suffix.device.manager'].replace(/\./g, '\\.')}`,
Feito.

2021-11-25 15:28 UTC, gilmaicor commented on iam/device-basic-authentication/app/kafka/ProducerMessages.js
> +      const kafkaTopic = `${tenant}.${topicSuffix}`;
ok.

2021-11-25 15:28 UTC, gilmaicor commented on iam/device-basic-authentication/config/default.conf
> +messenger.consume.topic.suffix.device.manager=dojot.device-manager.device
Feito.

2021-11-25 15:30 UTC, gilmaicor commented on connector/http-agent/README.md
> +| security.unsecure.mode.only | false         | boolean                     | HTTP_AGENT_SECURITY_UNSECURE_MODE_ONLY |
Eu fiz pensando no seu casso que só quer usar o http, mas pode haver situações onde eu quero tanto http quanto https.

2021-11-25 15:31 UTC, gilmaicor commented on connector/http-agent/app/express/interceptors/authorizationService.js
> +        [tenant, deviceId] = username.split('@');
Não terá mais parameter.

2021-11-25 16:18 UTC, gilmaicor commented on connector/http-agent/app/axios/CertificateAclService.js
> +    this.axios = createAxios();
Feito.

2021-11-25 18:40 UTC, luissajunior approved these changes

2021-11-25 19:17 UTC, rodrigoaasm approved these changes
Great!

2021-11-25 19:45 UTC, merged