fix: status code of response
dojot/dojot pull request #2345
Opened 2021-11-22 03:04 UTC by gilmaicor

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
* #2306
* #2315 

* **Other information**:

2021-11-22 16:10 UTC, rodrigoaasm approved these changes
Good job!

2021-11-24 13:34 UTC, cfrancisco requested changes

2021-11-24 13:34 UTC, cfrancisco commented on connector/http-agent/app/express/interceptors/deviceIdentification.js
> +    const BadRequest = new createError[400]();
It's creating 2 new Error Messages in all requests. It could be placed at the beginning of the file, as 'global'.

2021-11-24 13:34 UTC, cfrancisco commented on connector/http-agent/app/express/interceptors/deviceIdentification.js
> +    const BadRequest = new createError[400]();
It's creating 2 new Error Messages in all requests. It could be placed at the beginning of the file, as 'global'.

2021-11-24 13:34 UTC, cfrancisco commented on connector/http-agent/app/express/interceptors/deviceIdentification.js
> +    const BadRequest = new createError[400]();
It's creating 2 new Error Messages in all requests. It could be placed at the beginning of the file, as 'global' or...

2021-11-24 13:34 UTC, cfrancisco commented on connector/http-agent/app/express/interceptors/deviceIdentification.js
> +          Forbidden.message =
...or, you could only create the Error here (probably it's a better choice)

2021-11-24 13:34 UTC, cfrancisco commented on connector/http-agent/app/express/interceptors/deviceIdentification.js
>              'Error trying to get tenant and deviceId in CN of certificate.';
Hm... a 403 error is caused by invalid permissions, so your error message should mention that and signalize the user.
You got it right in: Forbidden.message = 'Client certificate is invalid';

2021-11-24 14:01 UTC, luissajunior approved these changes

2021-11-24 17:41 UTC, luissajunior submitted a review, later dismissed

2021-11-25 17:30 UTC, closed without merging