fix: parse timestamp
dojot/dojot pull request #2346
Opened 2021-11-22 05:03 UTC by gilmaicor

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
* #2319
* #2305 

* **Other information**:

2021-11-23 20:04 UTC, rodrigoaasm submitted a review, later dismissed
Looks great to me.

2021-11-24 13:52 UTC, cfrancisco requested changes

2021-11-24 13:52 UTC, cfrancisco commented on connector/http-agent/app/Utils.js
> +  // eslint-disable-next-line max-len
Hey... This is not fair haha. Remove it and split the line to follow the eslint.

2021-11-24 13:52 UTC, cfrancisco commented on connector/http-agent/app/Utils.js
> +  if (typeof str !== 'string') return false; // we only process strings!
If only process strings this is not an "isInteger" validation. Why not use "integer.parseint" ?

2021-11-24 13:52 UTC, cfrancisco commented on connector/http-agent/app/Utils.js
> +    throw err;
Vou escrever em portugues aqui para deixar melhor explicado.

Essa função está muito complicada de ler, apesar de em teoria fazer algo simples. Normalmente tente evitar ifs aninhados, além de abrir um fluxo a mais de operação, é prejudicial para entender. Isso é possivel de ser evitado por exemplo:
// if wasn't received ts value, return the current timestamp;
if (!ts){
     return new Date().getTime();
}

No caso colocar alguns comentários pode te ajudar a ver o fluxo da operação, nem sempre é bom por comentários (os principios do clean code evita), mas no começo não tem problemas. 

Além, tem código repetido como o 'new Date(parseInt(ts, 10)).getTime();', é melhor colocar ele em uma variavel auxiliar (com um bom nome) e fazer as operações com ele. Além de tudo, essa chamada cria um novo objeto e faz um parse, o que gasta recurso a toa da maquina. 


Por fim, melhor arrumar o ts antes de fazer as operações do que fazer 'if se ele é string ou inteiro'. Faz um parse dele para Inteiro antes e faz um fluxo unico depois.

2021-11-25 17:24 UTC, closed without merging