[DOJOT-54] Update: Consider attribute types for retrieval
dojot/dojot pull request #2609
Opened 2022-07-05 19:31 UTC by ademirr

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
https://dojot.atlassian.net/browse/DOJOT-54

* **Other information**:

2022-07-07 13:25 UTC, rodrigoaasm requested changes

2022-07-07 13:25 UTC, rodrigoaasm commented on storage/time-series/influxdb/retriever/test/integration/RoutesV1Device.test.js
> +const deviceDataRepository = new DeviceDataRepository('default_repository', mockInfluxDBConnection, true);
Esse último argumento, é para gravar em string né? Mas porque ele está definindo em hardcode? Não deveria ser um variável de ambiente?

2022-07-07 13:25 UTC, rodrigoaasm commented on storage/time-series/influxdb/retriever/test/unit/DeviceDataRepository.test.js
> +    dataQuery = new DataQuery('defaultBucket', mockInfluxDBConnection, true);
Esse último argumento, é para gravar em string né? Mas porque ele está definindo em hardcode? Não deveria ser um variável de ambiente?

2022-07-12 12:40 UTC, ademirr commented on storage/time-series/influxdb/retriever/test/integration/RoutesV1Device.test.js
> +const deviceDataRepository = new DeviceDataRepository('default_repository', mockInfluxDBConnection, true);
Nesse caso, como é uma classe de teste, sim, o hardcoded foi a melhor opção pra cobrir os cenários de testes. Já nas classes normais está pegando do arquivo default.conf.

2022-07-12 12:41 UTC, ademirr commented on storage/time-series/influxdb/retriever/test/unit/DeviceDataRepository.test.js
> +    dataQuery = new DataQuery('defaultBucket', mockInfluxDBConnection, true);
Nesse caso, como é uma classe de teste, sim, o hardcoded foi a melhor opção pra cobrir os cenários de testes. Já nas classes normais está pegando do arquivo default.conf.

2022-07-14 18:17 UTC, rodrigoaasm approved these changes
Approved, great job!

2022-07-19 11:32 UTC, merged