Feature/dojot 48 (deleção de device em lote - stale)
dojot/dojot pull request #2673
Opened 2022-10-17 13:16 UTC by MarceloPimentel050975

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature/dojo-48 create project device and template in batch.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-10-17 16:57 UTC, rodrigoaasm requested changes
The naming of some classes needs to be revised. I left more comments for other subjects

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/docker/dev/Dockerfile
> +CMD ["npm", "run", "dev"]
Como após o merge é feito o build para produção, não pode haver código em nível de dev.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/controller/devices_batch.ts
> +    try {
Existe um service nesse código, mas a operação está sendo realizada pelo controller. Não deveria ser feito dentro do service ? Porque existe um DTO se o objeto não é enviado para outra camada ?

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/controller/templates_batch.ts
> +        /*const device_associate = this.templatesServices.findByAssociateDevicesAndTemplate(id);
Porque esse código está comentado.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/index.ts
> +    const server = this.createServer();
O Eslint desse projeto não está funcionando corretamente. Algumas linhas terminam em ";" outras não.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/index.ts
> +    await this.kafkaConsumer.init()
Problemas de indexação.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/interceptors/ErrorHandler.interceptor.ts
> +      res.status(500).json({ message: error.message })
Deve se seguir as especificações do HTTP para devolução de erro. Nesse caso todos os erros são tratados como 500.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/interceptors/ErrorKeycloakHandler.interceptor.ts
> +export abstract class ErrorKeycloakHandlerInterceptor {
Todos os erros da aplicação deveriam ser tratados no mesmo local para inibir a complexidade e evitar chamadas inúteis.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/services/devicesServices.ts
> +import { Logger } from "@dojot/microservice-sdk";
Essa classe parece um repository pattern e não um service pattern.

2022-10-17 16:57 UTC, rodrigoaasm commented on batch/device-manager/src/app/services/templatesServices.ts
> +import { Logger } from "@dojot/microservice-sdk";
Essa classe é um repository pattern não um service pattern.

2022-10-25 14:38 UTC, rodrigoaasm requested changes
I left more commets.

2022-10-25 19:01 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/controller/templates_batch.ts
> +
Ainda não pois vai ser a próxima atividade, que já estou fazendo.

2022-10-25 19:01 UTC, MarceloPimentel050975 commented on batch/device-manager/docker/dev/Dockerfile
> +FROM node:14-alpine AS base
vou mudar para versão 16 seria isso?

2022-10-25 19:02 UTC, MarceloPimentel050975 commented on batch/device-manager/.editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
ok, vou adicionar.

2022-10-26 14:08 UTC, MarceloPimentel050975 commented on batch/device-manager/docker/dev/Dockerfile
> +FROM node:14-alpine AS base
Eu fiz já alteração da versão do nodejs.

2022-10-26 14:08 UTC, MarceloPimentel050975 commented on batch/device-manager/.editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
Blz, adicionando no gitignores.

2022-11-18 17:40 UTC, MarceloPimentel050975 commented
Close the PR with correction of code to remove devices and new features remove template.  

https://github.com/dojot/dojot/pull/2706

2022-11-18 18:33 UTC, rodrigoaasm approved these changes
Aprroved

2022-11-18 18:36 UTC, rodrigoaasm commented
Por falta de configuração do codecov e do codefactor estou forçando o merge.

2022-11-18 18:43 UTC, coutinhosantos submitted a review, later dismissed
OK

2022-11-18 18:46 UTC, merged