[DOJOT-150] add: Grafana dashboards with InfluxDB telemetry data.
dojot/dojot pull request #2681
Opened 2022-10-20 20:37 UTC by ademirr

…ata.

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

[DOJOT-150] is an epic with many stories. The stories referring to the grafana dashboards with InfluxDB telemetry data are:

[DOJOT-156]
[DOJOT-157]
[DOJOT-158]
[DOJOT-161]
[DOJOT-163]
[DOJOT-164]
[DOJOT-165]
[DOJOT-166]
[DOJOT-167]
[DOJOT-168]
[DOJOT-169]
[DOJOT-170]

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

https://dojot.atlassian.net/browse/DOJOT-156
https://dojot.atlassian.net/browse/DOJOT-157
https://dojot.atlassian.net/browse/DOJOT-158
https://dojot.atlassian.net/browse/DOJOT-161
https://dojot.atlassian.net/browse/DOJOT-163
https://dojot.atlassian.net/browse/DOJOT-164
https://dojot.atlassian.net/browse/DOJOT-165
https://dojot.atlassian.net/browse/DOJOT-166
https://dojot.atlassian.net/browse/DOJOT-167
https://dojot.atlassian.net/browse/DOJOT-168
https://dojot.atlassian.net/browse/DOJOT-169
https://dojot.atlassian.net/browse/DOJOT-170

* **Other information**:

2022-10-20 22:23 UTC, gabrielifg commented on data-visualization/grafana-templates/datasource.yml
> +      maxOpenConns: 0         # Grafana v5.4+
Uma sugestão, para deixar o código mais limpo, você pode tirar esses comentários "repetidos"

2022-10-20 22:24 UTC, gabrielifg approved these changes
Excelente trabalho!!!

2022-10-21 13:11 UTC, rodrigoaasm approved these changes
Ok

2022-10-28 22:43 UTC, gabrielifg requested changes

2022-10-28 22:43 UTC, gabrielifg commented on data-visualization/grafana-templates/datasource.yml
> +    type: PostgreSQL
O valor do type, deve estar dessa forma "postgres"

2022-10-28 22:43 UTC, gabrielifg commented on data-visualization/grafana-templates/datasource.yml
> +    type: InfluxDB
O valor do type, deve estar dessa forma "influxdb"

2022-10-28 22:43 UTC, gabrielifg commented on data-visualization/grafana-templates/datasource.yml
> +      timescaledb: false
Seria interessante adicionar ao final de ambos os datasource essas intruções para permitir a auteração e a escrita.

      readOnly: false
      editable: true

2022-11-22 20:12 UTC, rodrigoaasm approved these changes
Approved!

2022-11-23 01:48 UTC, gabrielifg approved these changes

2022-11-24 11:39 UTC, merged