Feature - Report Manager
dojot/dojot pull request #2698
Opened 2022-11-03 14:26 UTC by LuanEdCosta

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
Report Manager does not exit

* **What is the new behavior (if this is a feature change)?**
Report Manager code added 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
- GitHub action added
- Report Manager code added

2022-11-10 13:02 UTC, rodrigoaasm requested changes
Leave some comments.

2022-11-11 18:50 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/tests/integration/setup/App.setup.ts
> +  const app = new App(
**Por enquanto vamos deixar da forma que está, mas adicionei comentários mostrando como melhorar os testes de integração.**
Atualmente os testes de integração sobem todo o serviço e consomem rotas, então passa por todas as configs para subir o server HTTP com o express, passa pelas validações de rotas com o JOI, pelo controller, service e testa o retorno do controller. Então os testes atuais até testam a integração de unidades, mas ainda há espaço para remover alguns mocks e deixar os testes mais realistas.

2022-11-11 18:50 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/app/services/ReportFile.service.ts
> +import { PrismaClient } from '@prisma/client'
Mantive como service pois pode evoluir no futuro e para padronizar. Deixei um comentário explicando no código.

2022-11-11 18:51 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/app/services/ReportAttempt.service.ts
> +import { PrismaClient } from '@prisma/client'
Mantive como service pois pode evoluir no futuro e para padronizar. Deixei um comentário explicando no código.

2022-11-11 18:51 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/app/services/Device.service.ts
> +import { PrismaClient } from '@prisma/client'
Corrigido :+1:

2022-11-11 18:51 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/app/services/Report.service.ts
> +import { Logger } from '@dojot/microservice-sdk'
Corrigido :+1:

2022-11-11 18:51 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/app/controllers/Device.controller.ts
> +      await this.deviceReportQueue.createReport(report, {
Corrigido :+1:

2022-11-22 20:06 UTC, rascaraficci reviewed
Consegui olhar apenas alguns arquivos "na diagonal". Do meu ponto de vista o código está muito bem escrito.  Para tentar contribuir, deixei alguns comentários e sugestões.

2022-11-23 11:56 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/app/jobs/processors/DeviceReport.processor.ts
> +      const allDeviceData = await this.getAllDeviceData(report, param.id, token)
De fato o await "para o loop" até que a chamada assíncrona termine. A performance com o `for` é menor do que iniciar várias promises e aguardar no final o término de todas, mas em compensação a legibilidade do `for` é melhor.
Tem várias melhorias de performance que precisaremos fazer em uma nova versão do Report Manager, como por exemplo: separar o processamento dos jobs em outro processo do Node, criar um endpoint no Retriever que retorne mais dados de uma única vez (se possível), além de fazer a escrita em arquivos usando stream (porque atualmente o serviço vai acumulando os dados em memória sem nenhum limite até acabar de obter tudo e depois gera o CSV e PDF sem criar arquivo no disco).
Então acho que por enquanto podemos deixar desta forma, o impacto não é tão grande, mas tem muito espaço para evolução.

2022-11-23 12:16 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/kafka/TenantManager.kafka.ts
> +  async handleTenantEvent(payload: KafkaPayload) {
Verdade, vi aqui em outros serviços que faltou chamar o callback para notificar que processou a mensagem. Mas e se eu passar o `enable.async.commit: false`? 

---

![image](https://user-images.githubusercontent.com/36794274/203544520-cfe176ea-4953-4b27-9452-515f43df0c25.png)

2022-11-23 13:54 UTC, rodrigoaasm requested changes

2022-11-23 13:54 UTC, rodrigoaasm commented on data-visualization/reports/report-manager/src/kafka/TenantManager.kafka.ts
> +      const value = this.kafkaUtils.getValue(payload)
Vejo que existe nessa classe um acoplamento com Kafka. Essas transformações deveriam ocorrer no kafka-consumer.ts não nessa classe. Dessa forma existe um sobreposição de responsabilidades. O ack mencionado pelo Rafael também deve ocorrer no kafka-consumer.ts.

2022-11-23 16:28 UTC, rascaraficci commented on data-visualization/reports/report-manager/src/app/jobs/processors/DeviceReport.processor.ts
> +      const allDeviceData = await this.getAllDeviceData(report, param.id, token)
De acordo!

2022-11-23 16:34 UTC, rascaraficci commented on data-visualization/reports/report-manager/src/kafka/TenantManager.kafka.ts
> +  async handleTenantEvent(payload: KafkaPayload) {
Se passar a propriedade para false, o que acontece é que quando a callback de processamento finaliza, a biblioteca faz o commit para você. Tem cenários onde o processamento é assíncrono, ou seja, a callback finaliza, mas a mensagem não foi totalmente processada. Neste caso pode ocorrer perda da mensagem, por exemplo, o processamento não finalizou, o commit já foi feito e o serviço por algum motivo foi reiniciado. Precisa analisar qual é o caso aqui. Outro ponto a ser considerado, se existe algum outro mecanismo de sincronismo, uma eventual perda do dado não seria problema e poderia configurar a propriedade para false.

2022-11-23 16:42 UTC, LuanEdCosta commented on data-visualization/reports/report-manager/src/kafka/TenantManager.kafka.ts
> +  async handleTenantEvent(payload: KafkaPayload) {
Já estou implementando a chamada do callback para sinalizar a finalização do processamento. Também tinha um problema de inversão de responsabilidades que o Rodrigo comentou.

2022-11-23 19:53 UTC, LuanEdCosta commented
Realizei as correções e criei mais testes, agora a cobertura de testes aumentou:

![image](https://user-images.githubusercontent.com/36794274/203634894-70efb1a7-3368-47b1-bb0b-0c46074cdfa2.png)

2022-11-23 20:23 UTC, rascaraficci approved these changes
It looks good to me!

2022-11-24 12:01 UTC, rodrigoaasm approved these changes
Aprovado!

2022-11-24 12:31 UTC, merged