[DOJOT-144] Add: Receive measurement for device on and off.
dojot/dojot pull request #2699
Opened 2022-11-09 11:48 UTC by ademirr

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

https://dojot.atlassian.net/browse/DOJOT-144

* **Other information**:

2022-11-18 22:46 UTC, rodrigoaasm requested changes
Some language issues were encountered. Use English in your code.

2022-11-18 22:46 UTC, rodrigoaasm commented on connector/http-agent/app/express/interceptors/deviceValidatorInterceptor.js
> +    logger.debug(`Entrando no middleware ${TAG}`);
Logs apenas em inglês.

2022-11-18 22:46 UTC, rodrigoaasm commented on connector/http-agent/test/unit/deviceValidatorInterceptor.test.js
> +    expect(next.mock.calls[0][0]).toEqual('Device abc123 está desabilitado. A mensagem será descartada.');
Mensagens de saída também em inglês.

2022-11-22 16:26 UTC, rodrigoaasm requested changes
There are some problems in this PR!

2022-11-22 16:26 UTC, rodrigoaasm commented on connector/http-agent/test/integration/IncomingMessages.test.js
> +        mockDeviceManagerService.getDevice.mockReturnValue({ disabled: false });
Novamente, existe apenas testes com disabled=false.

2022-11-22 16:26 UTC, rodrigoaasm commented on connector/mqtt/vernemq/v2k-bridge/app/kafka/ConsumerMessages.js
> +    return async (data) => {
Atenção aqui ! O tratamento aqui está em modo sync.

2022-11-22 16:26 UTC, rodrigoaasm commented on connector/mqtt/vernemq/v2k-bridge/index.js
> +  setTimeout(async () => {
Esse setTimeout é uma má pratica. Caso seja necessário sincronizar os códigos use os recursos do js.

2022-11-23 17:33 UTC, ademirr commented on connector/http-agent/test/integration/IncomingMessages.test.js
> +        mockDeviceManagerService.getDevice.mockReturnValue({ disabled: false });
Teste feito.

2022-11-23 17:33 UTC, ademirr commented on connector/http-agent/test/integration/SchemaValidation.test.js
> +    mockDeviceManagerService.getDevice.mockReturnValue({ disabled: false });
Teste feito.

2022-11-23 17:39 UTC, ademirr commented on connector/mqtt/vernemq/v2k-bridge/app/kafka/ConsumerMessages.js
> +    return (data, ack) => {
Correção do async incluído no construtor do Consumer.

2022-11-23 17:41 UTC, ademirr commented on connector/mqtt/vernemq/v2k-bridge/index.js
> +  setTimeout(async () => {
setTimeout retirado.

2022-11-23 17:42 UTC, ademirr commented on connector/mqtt/vernemq/v2k-bridge/index.js
> +secretFileHandler.handle('keycloak.client.secret', '/secrets/').then(async () => {
async necessário por ter um await na chamada.

2022-11-23 18:08 UTC, rodrigoaasm approved these changes
Aprovado! Mas deixei um comentário que será relevante.

2022-11-24 11:31 UTC, merged