[dojot-48] Feature/device template deletion in batch kafka
dojot/dojot pull request #2706
Opened 2022-11-18 17:36 UTC by MarceloPimentel050975

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)
Create Batch Dojot-48 to remove devices and templates.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-11-18 22:42 UTC, rodrigoaasm requested changes
Need some changes. Another thing I noticed, you didn't use camelcase in all your code. Next time, use camelcase, please.

2022-11-18 22:42 UTC, rodrigoaasm commented on batch/device-manager/Dockerfile
> -RUN npm install
Estava na ordem correta. Dessa forma quando você alterar o código não precisará fazer o "npm install" novamente.

2022-11-18 22:42 UTC, rodrigoaasm commented on batch/device-manager/docker/dev/Dockerfile
> +COPY src ./src
O "npm install" sempre antes da copia do código.

2022-11-18 22:42 UTC, rodrigoaasm commented on batch/device-manager/src/app/repository/devicesRepository.ts
> +      return await prisma.devices.findMany({
Porque findMany ? O id não é único ?

2022-11-18 22:42 UTC, rodrigoaasm commented on batch/device-manager/src/app/repository/templatesRepository.ts
> +      return await prisma.templates.findMany({
Porque findMany ?

2022-11-21 11:13 UTC, MarceloPimentel050975 commented on batch/device-manager/docker/dev/Dockerfile
> +COPY src ./src
ok, vou ajustar npm install.

2022-11-21 11:38 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/templatesRepository.ts
> +      return await prisma.templates.findMany({
o FindMany estou utilizando para receber um array de Attrs e pegar a posição do template utilizo na linha, se colocar unique da erro na seleção do vetor da posição inicial. deviceService linha 291 
   attrs_found.push({ [template_id]: **assert_template_exists[0]**.attrs });

2022-11-21 11:46 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/devicesRepository.ts
> +      return await prisma.devices.findMany({
o FindMany estou utilizando para receber um array de templates e Attrs e pegar a posição do device utilizo na linha, se colocar unique não consigo checar se existe object no array com length.

2022-11-22 20:05 UTC, rodrigoaasm submitted a review, later dismissed
Approved!

2022-11-23 13:13 UTC, rodrigoaasm commented on batch/device-manager/src/app/repository/templatesRepository.ts
> +      return await prisma.templates.findMany({
Mas você não recebe um array de attrs, nesse caso você recebe um array de templates.

2022-11-23 13:18 UTC, rodrigoaasm commented on batch/device-manager/src/app/repository/devicesRepository.ts
> +      return await prisma.devices.findMany({
Nesse caso você recebe um array de templates com um único elemento. Se sempre vai retorna um único elemento não poderia ser find "many".  Deve haver outra forma de verificar.

2022-11-24 09:51 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/devicesRepository.ts
> +      return await prisma.devices.findMany({
Resolvido a mudança do tipo de busca findMany para findUnique.

2022-11-24 12:10 UTC, rodrigoaasm requested changes
Deixei mais alguns comentários que precisam de atenção. Verifique o CodeFactor porque ele está apontado alguns erros.

2022-11-24 12:51 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/devicesRepository.ts
> +      const error = e as Error;
Ok, vou tirar as try dos métodos do repositório.

2022-11-24 12:52 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/devicesRepository.ts
>          },
Ok, vou tirar as try dos métodos do repositório.

2022-11-24 12:52 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/devicesRepository.ts
>        const error = e as Error;
Ok, vou tirar as try dos métodos do repositório.

2022-11-24 12:52 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/attrsRepository.ts
> +      const error = e as Error;
Ok, vou tirar as try dos métodos do repositório.

2022-11-24 12:52 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/repository/devicesRepository.ts
>      } catch (e: unknown) {
Ok, vou tirar as try dos métodos do repositório.

2022-11-24 13:10 UTC, MarceloPimentel050975 commented on batch/device-manager/src/app/services/devicesServices.ts
> +            assert_device_exists.device_template.map(async (element: any) => {
Sim poderia vou corrigir

2022-11-24 17:38 UTC, rodrigoaasm approved these changes
Está aprovado. Mas Continue trabalhando nas questões levantadas.

2022-11-24 17:38 UTC, merged